version: '3'
services:
  rabbitmq:
    container_name: rabbitmq-server
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=root
      
    volumes:
      - "rabbitmq_data:/bitnami"
    networks:
      - net
      
  rabbit.web:
    image: nginx:1.17
    ports:
      - 81:80
    volumes:
      - ./web-php-code/web:/var/www/thehole
      - ./web-php-code/docker-config/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - net
  php:
    image: php:7.2-fpm
    volumes:
      - ./web-php-code/web:/var/www/thehole
    networks:
      - net
      
volumes:
  rabbitmq_data:
    driver: local

networks:
  net:
